version: "3.7"


services:
  camunda-db:
    container_name: camunda-db
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: camunda-db
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - ./postgres/camunda:/data/postgres:rw
    ports:
      - '5444:5432'
    restart: unless-stopped
    networks:
      - my-network

networks:
  my-network:
    driver: "bridge"

volumes:
  postgres: